name: Build and Release

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    
    - name: Setup NuGet
      uses: nuget/setup-nuget@v2
    
    - name: Restore NuGet packages
      run: nuget restore ROZeroLoginer.sln
    
    - name: Build solution
      run: msbuild ROZeroLoginer.sln /p:Configuration=Release /p:Platform="Any CPU" /p:OutputPath=bin\Release\
    
    - name: Prepare release files
      run: |
        mkdir release
        xcopy "ROZeroLoginer\bin\Release\*.exe" release\ /Y
        xcopy "ROZeroLoginer\bin\Release\*.dll" release\ /Y
        xcopy "ROZeroLoginer\bin\Release\*.config" release\ /Y
      shell: cmd
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ROZeroLoginer-Build
        path: release/
    
    - name: Create release archive
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        powershell Compress-Archive -Path release\* -DestinationPath ROZeroLoginer-${{ github.ref_name }}.zip
    
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: ROZeroLoginer ${{ github.ref_name }}
        body: |
          ## 🚀 新功能
          - ✨ 自動啟動遊戲並自動登入功能
          - 📝 批次修改帳號功能
          - 📂 分組標籤頁顯示功能
          - ☑️ 帳號全選/全不選/批次啟動功能
          - 🏷️ 版本號顯示在視窗標題
          
          ## 🔧 技術改進
          - ⏰ 優化 TOTP 生成，增加時間同步
          - 🎨 改進帳號選擇視窗介面
          - 💅 改善 UI 佈局和樣式
          - 📋 新增應用程式清單檔案
        draft: false
        prerelease: false
    
    - name: Upload Release Asset
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./ROZeroLoginer-${{ github.ref_name }}.zip
        asset_name: ROZeroLoginer-${{ github.ref_name }}.zip
        asset_content_type: application/zip